const Contact = require('../Model/contactModel')
const catchAsync = require('../utils/catchAsync')
// const AppError  = require('../utils/appError')
const handleFactory = require('./handleFactory')
exports.createNeworder = (handleFactory.Addnew(Contact))